impl Book, BookRepository, BookService
Petro-Smoliar/book_store pull request #1
Opened 2023-10-18 12:57 UTC by Petro-Smoliar

2023-10-18 19:09 UTC, Ivan95kos requested changes
Good job overall!

2023-10-18 19:09 UTC, Ivan95kos commented on src/main/java/com/example/book/store/config/AppConfig.java
> +public class AppConfig {
In the first steps, it is better to use the default Beans
You can remove this config

2023-10-18 19:09 UTC, Ivan95kos commented on src/main/java/com/example/book/store/model/Book.java
> +public class Book {
Use the library Lombok
then you will be able to use the annotations like @Data, @Setter, @Getter

2023-10-18 19:09 UTC, Ivan95kos commented on src/test/java/com/example/book/store/BookStoreApplicationTests.java
>  @SpringBootTest
```suggestion
@SpringBootTest(classes = BookStoreApplicationTests.class)
```

2023-10-18 19:09 UTC, Ivan95kos commented on src/test/java/com/example/book/store/BookStoreApplicationTests.java
> -	}
This test must be present, revert it

2023-10-23 10:53 UTC, kozhukhovsky approved these changes

2023-10-25 11:59 UTC, kozhukhovsky approved these changes

2023-10-28 13:36 UTC, merged